// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {screencast} from '../models';
import {main} from '../models';

export function CancelPaletteAreaCapture():Promise<void>;

export function CancelRecording():Promise<void>;

export function CompletePaletteAreaScreenshot(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function DeleteScreenshot(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetRecordingsBaseURL():Promise<string>;

export function GetSavedMicrophone():Promise<string>;

export function GetScreenshotsBaseURL():Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetSystemAudioSupported():Promise<screencast.SystemAudioInfo>;

export function GetVideosDir():Promise<string>;

export function ListMicrophones():Promise<Array<screencast.AudioDevice>>;

export function ListRecordings():Promise<Array<main.RecordingInfo>>;

export function ListScreenshots():Promise<Array<main.ScreenshotInfo>>;

export function OpenToolsPalette():Promise<void>;

export function PauseRecording():Promise<void>;

export function RenameScreenshot(arg1:string,arg2:string):Promise<void>;

export function ResetSettings():Promise<settings.Settings>;

export function ResizeToPalette():Promise<void>;

export function ResizeToPreferences():Promise<void>;

export function ResizeToRecord():Promise<void>;

export function ResizeToSettings():Promise<void>;

export function ResizeToStudio():Promise<void>;

export function ResumeRecording():Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveMicrophone(arg1:string):Promise<void>;

export function SaveRecordingDefaults(arg1:boolean,arg2:boolean,arg3:boolean):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SetMicEnabled(arg1:boolean):Promise<void>;

export function SetSystemEnabled(arg1:boolean):Promise<void>;

export function StartPaletteAreaCapture():Promise<string>;

export function StartRecording(arg1:boolean,arg2:boolean,arg3:boolean,arg4:string):Promise<string>;

export function StopRecording():Promise<string>;

export function TakeAreaScreenshot():Promise<void>;

export function TakeScreenshot():Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;
