// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPaletteAreaCapture() {
  return window['go']['main']['App']['CancelPaletteAreaCapture']();
}

export function CancelRecording() {
  return window['go']['main']['App']['CancelRecording']();
}

export function CompletePaletteAreaScreenshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompletePaletteAreaScreenshot'](arg1, arg2, arg3, arg4);
}

export function DeleteScreenshot(arg1) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetRecordingsBaseURL() {
  return window['go']['main']['App']['GetRecordingsBaseURL']();
}

export function GetSavedMicrophone() {
  return window['go']['main']['App']['GetSavedMicrophone']();
}

export function GetScreenshotsBaseURL() {
  return window['go']['main']['App']['GetScreenshotsBaseURL']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemAudioSupported() {
  return window['go']['main']['App']['GetSystemAudioSupported']();
}

export function GetVideosDir() {
  return window['go']['main']['App']['GetVideosDir']();
}

export function ListMicrophones() {
  return window['go']['main']['App']['ListMicrophones']();
}

export function ListRecordings() {
  return window['go']['main']['App']['ListRecordings']();
}

export function ListScreenshots() {
  return window['go']['main']['App']['ListScreenshots']();
}

export function OpenToolsPalette() {
  return window['go']['main']['App']['OpenToolsPalette']();
}

export function PauseRecording() {
  return window['go']['main']['App']['PauseRecording']();
}

export function RenameScreenshot(arg1, arg2) {
  return window['go']['main']['App']['RenameScreenshot'](arg1, arg2);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function ResizeToPalette() {
  return window['go']['main']['App']['ResizeToPalette']();
}

export function ResizeToPreferences() {
  return window['go']['main']['App']['ResizeToPreferences']();
}

export function ResizeToRecord() {
  return window['go']['main']['App']['ResizeToRecord']();
}

export function ResizeToSettings() {
  return window['go']['main']['App']['ResizeToSettings']();
}

export function ResizeToStudio() {
  return window['go']['main']['App']['ResizeToStudio']();
}

export function ResumeRecording() {
  return window['go']['main']['App']['ResumeRecording']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveMicrophone(arg1) {
  return window['go']['main']['App']['SaveMicrophone'](arg1);
}

export function SaveRecordingDefaults(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRecordingDefaults'](arg1, arg2, arg3);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SetMicEnabled(arg1) {
  return window['go']['main']['App']['SetMicEnabled'](arg1);
}

export function SetSystemEnabled(arg1) {
  return window['go']['main']['App']['SetSystemEnabled'](arg1);
}

export function StartPaletteAreaCapture() {
  return window['go']['main']['App']['StartPaletteAreaCapture']();
}

export function StartRecording(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartRecording'](arg1, arg2, arg3, arg4);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function TakeAreaScreenshot() {
  return window['go']['main']['App']['TakeAreaScreenshot']();
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
